stages:
  - build
  - release


release-build:
   stage: build
   tags: 
     - rust
   rules:
     - if: $CI_COMMIT_BRANCH == "release"
   script:
     - echo "installing dependencies"
     - apk add musl-dev openssl
     - echo "Building Release"
     - cargo build -r --verbose
