stages:
  - build
  - release


release-build:
   stage: build
   tags: 
     - rust
   rules:
     - if: $CI_COMMIT_BRANCH == "release"
   script:
     - echo "installing dependencies"
     - apk update && apk add pkgconf build-base libressl-dev=3.9.2-r0 alsa-lib-dev
     - echo "Building Release"
     - cargo build -r --verbose
     - ls -l
