name: Rust

on:
  push:
    branches: [ "release" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: sudo apt-get update && sudo apt-get install --assume-yes libssl-dev libasound2-dev
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: save build
      uses: actions/upload-artifact@v4
      with:
        name: executable
        path: target/release/IDDiaplay
